version: "3.9"
services:
  apirecetas:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - mongo_recetas
    volumes:
      - .:/home/app
  mongo_recetas:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=poli
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: